/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2019-01-08 11:13:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.axis2.context.ConfigurationContext;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang.ArrayUtils;
import org.apache.commons.lang.StringUtils;
import org.owasp.encoder.Encode;
import org.wso2.carbon.CarbonConstants;
import org.wso2.carbon.ui.CarbonUIUtil;
import org.wso2.carbon.user.mgt.stub.types.carbon.FlaggedName;
import org.wso2.carbon.user.mgt.stub.types.carbon.UserRealmInfo;
import org.wso2.carbon.user.mgt.ui.PaginatedNamesBean;
import org.wso2.carbon.user.mgt.ui.UserAdminClient;
import org.wso2.carbon.user.mgt.ui.UserAdminUIConstants;
import org.wso2.carbon.user.mgt.ui.UserManagementWorkflowServiceClient;
import org.wso2.carbon.user.mgt.ui.Util;
import org.wso2.carbon.utils.ServerConstants;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Set;

public final class view_002droles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/tlds/carbontags.tld", Long.valueOf(1472217474000L));
    _jspx_dependants.put("/WEB-INF/tlds/fmt.tld", Long.valueOf(1472217474000L));
    _jspx_dependants.put("/WEB-INF/tlds/csrfguard.tld", Long.valueOf(1472217474000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcarbon_005fbreadcrumb_0026_005ftopPage_005fresourceBundle_005frequest_005flabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcarbon_005fpaginator_0026_005fparameters_005fpageNumberParameterName_005fpageNumber_005fpage_005fnumberOfPages_005fnoOfPageLinksToDisplay_005faction_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcarbon_005fbreadcrumb_0026_005ftopPage_005fresourceBundle_005frequest_005flabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcarbon_005fpaginator_0026_005fparameters_005fpageNumberParameterName_005fpageNumber_005fpage_005fnumberOfPages_005fnoOfPageLinksToDisplay_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename.release();
    _005fjspx_005ftagPool_005fcarbon_005fbreadcrumb_0026_005ftopPage_005fresourceBundle_005frequest_005flabel_005fnobody.release();
    _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.release();
    _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fcarbon_005fpaginator_0026_005fparameters_005fpageNumberParameterName_005fpageNumber_005fpage_005fnumberOfPages_005fnoOfPageLinksToDisplay_005faction_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../userstore/extensions/js/vui.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../admin/js/main.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../identity/validation/js/identity-validate.js\"></script>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../dialog/display_messages.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../userstore/display-messages.jsp", out, false);
      out.write('\n');
      out.write('\n');
      out.write('\n');

    String BUNDLE = "org.wso2.carbon.userstore.ui.i18n.Resources";
    ResourceBundle resourceBundle = ResourceBundle.getBundle(BUNDLE, request.getLocale());

    boolean showFilterMessage = false;
    boolean newFilter = false;
    boolean doUserList = true;
    boolean showUpdate = true;
    FlaggedName exceededDomains = null;
    FlaggedName[] roles = null;
    int pageNumber = 0;
    int cachePages = 3;
    int noOfPageLinksToDisplay = 5;
    int numberOfPages = 0;
    Map<Integer, PaginatedNamesBean> flaggedNameMap = null;
    Set<String> workFlowDeletePendingRoles = null;

    if (request.getParameter("pageNumber") == null) {
        session.removeAttribute("checkedRolesMap");
    }
    if (session.getAttribute("checkedRolesMap") == null) {
        session.setAttribute("checkedRolesMap", new HashMap<String, Boolean>());
    }

    session.removeAttribute("prevString");
    session.removeAttribute(UserAdminUIConstants.ROLE_LIST_ASSIGNED_USER_CACHE);
    session.removeAttribute(UserAdminUIConstants.ROLE_LIST_ASSIGNED_USER_CACHE_EXCEEDED);
    session.removeAttribute(UserAdminUIConstants.ROLE_LIST_VIEW_USER_FILTER);
    session.removeAttribute(UserAdminUIConstants.USER_LIST_ASSIGNED_ROLE_CACHE);
    session.removeAttribute(UserAdminUIConstants.USER_LIST_ASSIGNED_ROLE_CACHE_EXCEEDED);

    // search filter
    String filter = request.getParameter(UserAdminUIConstants.USER_LIST_VIEW_ROLE_FILTER);
    if (StringUtils.isBlank(filter)) {
        filter = (java.lang.String) session.getAttribute(UserAdminUIConstants.USER_LIST_VIEW_ROLE_FILTER);
        if (StringUtils.isBlank(filter)) {
            filter = "*";
        }
    } else {
        newFilter = true;
    }
    filter = filter.trim();
    session.setAttribute(UserAdminUIConstants.USER_LIST_VIEW_ROLE_FILTER, filter);

    // check page number
    try {

        pageNumber = Integer.parseInt(request.getParameter("pageNumber"));

    } catch (NumberFormatException ignored) {
        // page number format exception
        pageNumber = 0;
    }

    flaggedNameMap = (Map<Integer, PaginatedNamesBean>) session.
            getAttribute(UserAdminUIConstants.USER_LIST_ASSIGNED_ROLE_CACHE);
    if (flaggedNameMap != null) {
        PaginatedNamesBean bean = flaggedNameMap.get(pageNumber);
        if (bean != null) {
            roles = bean.getNames();
            if (ArrayUtils.isNotEmpty(roles)) {
                numberOfPages = bean.getNumberOfPages();
                doUserList = false;
            }
        }
    }

    String userName = request.getParameter("username");
    String displayName = request.getParameter("displayName");
    if (StringUtils.isBlank(displayName)) {
        displayName = (String) session.getAttribute(UserAdminUIConstants.USER_DISPLAY_NAME);
        if (StringUtils.isBlank(displayName)) {
            displayName = userName;
        }
    } else {
        session.setAttribute(UserAdminUIConstants.USER_DISPLAY_NAME, displayName);
    }
    UserRealmInfo userRealmInfo = (UserRealmInfo) session.getAttribute(UserAdminUIConstants.USER_STORE_INFO);
    exceededDomains = (FlaggedName) session.getAttribute(UserAdminUIConstants.USER_LIST_ASSIGNED_ROLE_CACHE_EXCEEDED);

    if(doUserList || newFilter){
        try {

            String cookie = (String) session.getAttribute(ServerConstants.ADMIN_SERVICE_COOKIE);
            String backendServerURL = CarbonUIUtil.getServerURL(config.getServletContext(), session);
            ConfigurationContext configContext =
                    (ConfigurationContext) config.getServletContext().getAttribute(CarbonConstants.CONFIGURATION_CONTEXT);
            UserAdminClient client = new UserAdminClient(cookie, backendServerURL, configContext);
            UserManagementWorkflowServiceClient UserMgtClient = new
                    UserManagementWorkflowServiceClient(cookie, backendServerURL, configContext);

            if (filter.length() > 0 && userName != null) {
                FlaggedName[] data = client.getRolesOfUser(userName, filter, 0);
                if (CarbonUIUtil.isContextRegistered(config, "/usermgt-workflow/")) {
                    String[] DeletePendingRolesList = UserMgtClient.
                            listAllEntityNames("DELETE_ROLE", "PENDING", "ROLE", filter);
                    workFlowDeletePendingRoles = new LinkedHashSet<String>(Arrays.asList(DeletePendingRolesList));
                    String pendingStatus = "[Pending Role for Delete]";

                    if (data != null) {
                        for (int i = 0; i < data.length; i++) {
                            String updatedStatus = null;
                            if (workFlowDeletePendingRoles.contains(data[i].getItemName())) {
                                updatedStatus = data[i].getItemName() + " " + pendingStatus;
                                data[i].setItemDisplayName(data[i].getItemName());
                                data[i].setItemName(updatedStatus);
                            }
                        }
                    }
                }
                List<FlaggedName> dataList = new ArrayList<FlaggedName>(Arrays.asList(data));
                exceededDomains = dataList.remove(dataList.size() - 1);
                session.setAttribute(UserAdminUIConstants.USER_LIST_ASSIGNED_ROLE_CACHE_EXCEEDED, exceededDomains);
                if (CollectionUtils.isNotEmpty(dataList)) {
                    flaggedNameMap = new HashMap<Integer, PaginatedNamesBean>();
                    int max = pageNumber + cachePages;
                    for (int i = (pageNumber - cachePages); i < max; i++) {
                        if (i < 0) {
                            max++;
                            continue;
                        }
                        PaginatedNamesBean bean = Util.
                                retrievePaginatedFlaggedName(i, dataList);
                        flaggedNameMap.put(i, bean);
                        if (bean.getNumberOfPages() == i + 1) {
                            break;
                        }
                    }
                    roles = flaggedNameMap.get(pageNumber).getNames();
                    numberOfPages = flaggedNameMap.get(pageNumber).getNumberOfPages();
                    session.setAttribute(UserAdminUIConstants.USER_LIST_ASSIGNED_ROLE_CACHE, flaggedNameMap);
                } else {
                    session.removeAttribute(UserAdminUIConstants.USER_LIST_VIEW_ROLE_FILTER);
                    showFilterMessage = true;
                }
            }

            if (userRealmInfo == null) {
                userRealmInfo = client.getUserRealmInfo();
                session.setAttribute(UserAdminUIConstants.USER_STORE_INFO, userRealmInfo);
            }
        } catch (Exception e) {
            String message = MessageFormat.format(resourceBundle.getString("error.while.loading.roles.of"),
                    userName, e.getMessage());

      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    jQuery(document).ready(function () {\n");
      out.write("        CARBON.showErrorDialog('");
      out.print(Encode.forJavaScript(Encode.forHtml(message)));
      out.write("', function () {\n");
      out.write("            location.href = \"user-mgt.jsp\";\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");

        }
    }
    Util.updateCheckboxStateMap((Map<String,Boolean>)session.getAttribute("checkedRolesMap"),flaggedNameMap,
            request.getParameter("selectedRoles"),request.getParameter("unselectedRoles"),":");

      out.write('\n');
      //  fmt:bundle
      org.apache.taglibs.standard.tag.rt.fmt.BundleTag _jspx_th_fmt_005fbundle_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.BundleTag) _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename.get(org.apache.taglibs.standard.tag.rt.fmt.BundleTag.class);
      _jspx_th_fmt_005fbundle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fbundle_005f0.setParent(null);
      // /user/view-roles.jsp(212,0) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fbundle_005f0.setBasename("org.wso2.carbon.userstore.ui.i18n.Resources");
      int _jspx_eval_fmt_005fbundle_005f0 = _jspx_th_fmt_005fbundle_005f0.doStartTag();
      if (_jspx_eval_fmt_005fbundle_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fbundle_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_fmt_005fbundle_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_fmt_005fbundle_005f0.doInitBody();
        }
        do {
          out.write("\n");
          out.write("    ");
          //  carbon:breadcrumb
          org.wso2.carbon.ui.taglibs.Breadcrumb _jspx_th_carbon_005fbreadcrumb_005f0 = (org.wso2.carbon.ui.taglibs.Breadcrumb) _005fjspx_005ftagPool_005fcarbon_005fbreadcrumb_0026_005ftopPage_005fresourceBundle_005frequest_005flabel_005fnobody.get(org.wso2.carbon.ui.taglibs.Breadcrumb.class);
          _jspx_th_carbon_005fbreadcrumb_005f0.setPageContext(_jspx_page_context);
          _jspx_th_carbon_005fbreadcrumb_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
          // /user/view-roles.jsp(213,4) name = label type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fbreadcrumb_005f0.setLabel("users.in.the.role");
          // /user/view-roles.jsp(213,4) name = resourceBundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fbreadcrumb_005f0.setResourceBundle("org.wso2.carbon.userstore.ui.i18n.Resources");
          // /user/view-roles.jsp(213,4) name = topPage type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fbreadcrumb_005f0.setTopPage(true);
          // /user/view-roles.jsp(213,4) name = request type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fbreadcrumb_005f0.setRequest(request);
          int _jspx_eval_carbon_005fbreadcrumb_005f0 = _jspx_th_carbon_005fbreadcrumb_005f0.doStartTag();
          if (_jspx_th_carbon_005fbreadcrumb_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fcarbon_005fbreadcrumb_0026_005ftopPage_005fresourceBundle_005frequest_005flabel_005fnobody.reuse(_jspx_th_carbon_005fbreadcrumb_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fcarbon_005fbreadcrumb_0026_005ftopPage_005fresourceBundle_005frequest_005flabel_005fnobody.reuse(_jspx_th_carbon_005fbreadcrumb_005f0);
          out.write("\n");
          out.write("\n");
          out.write("    <script type=\"text/javascript\">\n");
          out.write("\n");
          out.write("        function doValidation() {\n");
          out.write("            // no worth of validation here.\n");
          out.write("            return true;\n");
          out.write("        }\n");
          out.write("\n");
          out.write("        function enableCheckBoxes() {\n");
          out.write("            var formElems = document.getElementsByName('selectedRoles');\n");
          out.write("            for (var i = 0; i < formElems.length; i++) {\n");
          out.write("                formElems[i].disabled = false;\n");
          out.write("            }\n");
          out.write("            return true;\n");
          out.write("        }\n");
          out.write("\n");
          out.write("        function doUpdate() {\n");
          out.write("            document.edit_users.submit();\n");
          out.write("        }\n");
          out.write("\n");
          out.write("        function doCancel() {\n");
          out.write("            location.href = 'user-mgt.jsp?ordinal=1';\n");
          out.write("        }\n");
          out.write("\n");
          out.write("        function doFinish() {\n");
          out.write("\n");
          out.write("            document.edit_users.finish.value = 'true';\n");
          out.write("            document.edit_users.submit();\n");
          out.write("\n");
          out.write("        }\n");
          out.write("\n");
          out.write("        function doPaginate(page, pageNumberParameterName, pageNumber) {\n");
          out.write("            var form = document.createElement(\"form\");\n");
          out.write("            form.id = \"paginateForm\";\n");
          out.write("            form.setAttribute(\"method\", \"POST\");\n");
          out.write("            form.setAttribute(\"action\", page + \"?\" + pageNumberParameterName + \"=\" + pageNumber + \"&username=\" + '");
          out.print(Encode.forJavaScript(Encode.forUriComponent(userName)));
          out.write("');\n");
          out.write("            var selectedRolesStr = \"\";\n");
          out.write("            $(\"input[type='checkbox']:checked\").each(function (index) {\n");
          out.write("                if (!$(this).is(\":disabled\")) {\n");
          out.write("                    selectedRolesStr += $(this).val();\n");
          out.write("                    if (index != $(\"input[type='checkbox']:checked\").length - 1) {\n");
          out.write("                        selectedRolesStr += \":\";\n");
          out.write("                    }\n");
          out.write("                }\n");
          out.write("            });\n");
          out.write("            var selectedRolesElem = document.createElement(\"input\");\n");
          out.write("            selectedRolesElem.setAttribute(\"type\", \"hidden\");\n");
          out.write("            selectedRolesElem.setAttribute(\"name\", \"selectedRoles\");\n");
          out.write("            selectedRolesElem.setAttribute(\"value\", selectedRolesStr);\n");
          out.write("            form.appendChild(selectedRolesElem);\n");
          out.write("            var unselectedRolesStr = \"\";\n");
          out.write("            $(\"input[type='checkbox']:not(:checked)\").each(function (index) {\n");
          out.write("                if (!$(this).is(\":disabled\")) {\n");
          out.write("                    unselectedRolesStr += $(this).val();\n");
          out.write("                    if (index != $(\"input[type='checkbox']:not(:checked)\").length - 1) {\n");
          out.write("                        unselectedRolesStr += \":\";\n");
          out.write("                    }\n");
          out.write("                }\n");
          out.write("            });\n");
          out.write("            var unselectedRolesElem = document.createElement(\"input\");\n");
          out.write("            unselectedRolesElem.setAttribute(\"type\", \"hidden\");\n");
          out.write("            unselectedRolesElem.setAttribute(\"name\", \"unselectedRoles\");\n");
          out.write("            unselectedRolesElem.setAttribute(\"value\", unselectedRolesStr);\n");
          out.write("            form.appendChild(unselectedRolesElem);\n");
          out.write("            var CSRFTokenElem = document.createElement(\"input\");\n");
          out.write("            CSRFTokenElem.setAttribute(\"type\", \"hidden\");\n");
          out.write("            CSRFTokenElem.setAttribute(\"name\", \"");
          if (_jspx_meth_csrf_005ftokenname_005f0(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\");\n");
          out.write("            CSRFTokenElem.setAttribute(\"value\", \"");
          if (_jspx_meth_csrf_005ftokenvalue_005f0(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\");\n");
          out.write("            form.appendChild(CSRFTokenElem);\n");
          out.write("            document.body.appendChild(form);\n");
          out.write("            $(\"#paginateForm\").submit();\n");
          out.write("        }\n");
          out.write("\n");
          out.write("        function doSelectAllRetrieved() {\n");
          out.write("            var form = document.createElement(\"form\");\n");
          out.write("            form.id = \"selectAllRetrievedForm\";\n");
          out.write("            form.setAttribute(\"method\", \"POST\");\n");
          out.write("            form.setAttribute(\"action\", \"view-roles.jsp?pageNumber=\" + ");
          out.print(pageNumber);
          out.write(" +\"&username=\" + '");
          out.print(Encode.forJavaScript(Encode.forUriComponent(userName)));
          out.write("');\n");
          out.write("            var selectedRolesElem = document.createElement(\"input\");\n");
          out.write("            selectedRolesElem.setAttribute(\"type\", \"hidden\");\n");
          out.write("            selectedRolesElem.setAttribute(\"name\", \"selectedRoles\");\n");
          out.write("            selectedRolesElem.setAttribute(\"value\", \"ALL\");\n");
          out.write("            form.appendChild(selectedRolesElem);\n");
          out.write("            var CSRFTokenElem = document.createElement(\"input\");\n");
          out.write("            CSRFTokenElem.setAttribute(\"type\", \"hidden\");\n");
          out.write("            CSRFTokenElem.setAttribute(\"name\", \"");
          if (_jspx_meth_csrf_005ftokenname_005f1(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\");\n");
          out.write("            CSRFTokenElem.setAttribute(\"value\", \"");
          if (_jspx_meth_csrf_005ftokenvalue_005f1(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\");\n");
          out.write("            form.appendChild(CSRFTokenElem);\n");
          out.write("            document.body.appendChild(form);\n");
          out.write("            $(\"#selectAllRetrievedForm\").submit();\n");
          out.write("        }\n");
          out.write("\n");
          out.write("        function doUnSelectAllRetrieved() {\n");
          out.write("            var form = document.createElement(\"form\");\n");
          out.write("            form.id = \"unSelectAllRetrievedForm\";\n");
          out.write("            form.setAttribute(\"method\", \"POST\");\n");
          out.write("            form.setAttribute(\"action\", \"view-roles.jsp?pageNumber=\" + ");
          out.print(pageNumber);
          out.write(" +\"&username=\" + '");
          out.print(Encode.forJavaScript(Encode.forUriComponent(userName)));
          out.write("');\n");
          out.write("            var unselectedRolesElem = document.createElement(\"input\");\n");
          out.write("            unselectedRolesElem.setAttribute(\"type\", \"hidden\");\n");
          out.write("            unselectedRolesElem.setAttribute(\"name\", \"unselectedRoles\");\n");
          out.write("            unselectedRolesElem.setAttribute(\"value\", \"ALL\");\n");
          out.write("            form.appendChild(unselectedRolesElem);\n");
          out.write("            var CSRFTokenElem = document.createElement(\"input\");\n");
          out.write("            CSRFTokenElem.setAttribute(\"type\", \"hidden\");\n");
          out.write("            CSRFTokenElem.setAttribute(\"name\", \"");
          if (_jspx_meth_csrf_005ftokenname_005f2(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\");\n");
          out.write("            CSRFTokenElem.setAttribute(\"value\", \"");
          if (_jspx_meth_csrf_005ftokenvalue_005f2(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\");\n");
          out.write("            form.appendChild(CSRFTokenElem);\n");
          out.write("            document.body.appendChild(form);\n");
          out.write("            $(\"#unSelectAllRetrievedForm\").submit();\n");
          out.write("        }\n");
          out.write("\n");
          out.write("        $(document).ready(function () {\n");
          out.write("            $('form[name=filterForm]').submit(function(){\n");
          out.write("                return doValidateForm(this, '");
          if (_jspx_meth_fmt_005fmessage_005f0(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("');\n");
          out.write("            })\n");
          out.write("        });\n");
          out.write("\n");
          out.write("    </script>\n");
          out.write("\n");
          out.write("\n");
          out.write("    <div id=\"middle\">\n");
          out.write("        <h2>");
          if (_jspx_meth_fmt_005fmessage_005f1(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write(' ');
          out.print(Encode.forHtml(displayName));
          out.write("\n");
          out.write("        </h2>\n");
          out.write("\n");
          out.write("        <script type=\"text/javascript\">\n");
          out.write("\n");
          out.write("            ");
if(showFilterMessage == true){
          out.write("\n");
          out.write("            CARBON.showInfoDialog('");
          if (_jspx_meth_fmt_005fmessage_005f2(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("', null, null);\n");
          out.write("            ");
}
          out.write("\n");
          out.write("\n");
          out.write("        </script>\n");
          out.write("        <div id=\"workArea\">\n");
          out.write("            <form name=\"filterForm\" method=\"post\"\n");
          out.write("                  action=\"view-roles.jsp?username=");
          out.print(Encode.forUriComponent(userName));
          out.write("\">\n");
          out.write("                <table class=\"normal\">\n");
          out.write("                    <tr>\n");
          out.write("                        <td>");
          if (_jspx_meth_fmt_005fmessage_005f3(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("</td>\n");
          out.write("                        <td>\n");
          out.write("                            <input type=\"text\" name=\"");
          out.print(UserAdminUIConstants.USER_LIST_VIEW_ROLE_FILTER);
          out.write("\"\n");
          out.write("                                   value=\"");
          out.print(Encode.forHtmlAttribute(filter));
          out.write("\" label=\"");
          if (_jspx_meth_fmt_005fmessage_005f4(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\"\n");
          out.write("                                   black-list-patterns=\"xml-meta-exists\"/>\n");
          out.write("                        </td>\n");
          out.write("                        <td>\n");
          out.write("                            <input class=\"button\" type=\"submit\"\n");
          out.write("                                   value=\"");
          if (_jspx_meth_fmt_005fmessage_005f5(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\"/>\n");
          out.write("                        </td>\n");
          out.write("                    </tr>\n");
          out.write("                </table>\n");
          out.write("            </form>\n");
          out.write("            <p>&nbsp;</p>\n");
          out.write("\n");
          out.write("            ");
          //  carbon:paginator
          org.wso2.carbon.ui.taglibs.Paginator _jspx_th_carbon_005fpaginator_005f0 = (org.wso2.carbon.ui.taglibs.Paginator) _005fjspx_005ftagPool_005fcarbon_005fpaginator_0026_005fparameters_005fpageNumberParameterName_005fpageNumber_005fpage_005fnumberOfPages_005fnoOfPageLinksToDisplay_005faction_005fnobody.get(org.wso2.carbon.ui.taglibs.Paginator.class);
          _jspx_th_carbon_005fpaginator_005f0.setPageContext(_jspx_page_context);
          _jspx_th_carbon_005fpaginator_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
          // /user/view-roles.jsp(367,12) name = pageNumber type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f0.setPageNumber(pageNumber);
          // /user/view-roles.jsp(367,12) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f0.setAction("post");
          // /user/view-roles.jsp(367,12) name = numberOfPages type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f0.setNumberOfPages(numberOfPages);
          // /user/view-roles.jsp(367,12) name = noOfPageLinksToDisplay type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f0.setNoOfPageLinksToDisplay(noOfPageLinksToDisplay);
          // /user/view-roles.jsp(367,12) name = page type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f0.setPage("view-roles.jsp");
          // /user/view-roles.jsp(367,12) name = pageNumberParameterName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f0.setPageNumberParameterName("pageNumber");
          // /user/view-roles.jsp(367,12) name = parameters type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f0.setParameters("username=" + Encode.forHtmlAttribute(userName));
          int _jspx_eval_carbon_005fpaginator_005f0 = _jspx_th_carbon_005fpaginator_005f0.doStartTag();
          if (_jspx_th_carbon_005fpaginator_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fcarbon_005fpaginator_0026_005fparameters_005fpageNumberParameterName_005fpageNumber_005fpage_005fnumberOfPages_005fnoOfPageLinksToDisplay_005faction_005fnobody.reuse(_jspx_th_carbon_005fpaginator_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fcarbon_005fpaginator_0026_005fparameters_005fpageNumberParameterName_005fpageNumber_005fpage_005fnumberOfPages_005fnoOfPageLinksToDisplay_005faction_005fnobody.reuse(_jspx_th_carbon_005fpaginator_005f0);
          out.write("\n");
          out.write("            <form method=\"post\" action=\"edit-user-roles-finish-ajaxprocessor.jsp?viewRoles=true\" onsubmit=\"return doValidation();\"\n");
          out.write("                  name=\"edit_users\" id=\"edit_users\">\n");
          out.write("                <input type=\"hidden\" id=\"username\" name=\"username\" value=\"");
          out.print(Encode.forHtmlAttribute(userName));
          out.write("\"/>\n");
          out.write("                <input type=\"hidden\" id=\"logout\" name=\"logout\" value=\"false\"/>\n");
          out.write("                <input type=\"hidden\" id=\"finish\" name=\"finish\" value=\"false\"/>\n");
          out.write("\n");
          out.write("                <div class=\"sectionHelp\">");
          if (_jspx_meth_fmt_005fmessage_005f6(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("</div>\n");
          out.write("                <table class=\"styledLeft\" id=\"table_users_list_of_role\">\n");
          out.write("                    <thead>\n");
          out.write("                    <tr>\n");
          out.write("                        <th>");
          if (_jspx_meth_fmt_005fmessage_005f7(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write(" <strong>");
          out.print(Encode.forHtml(userName));
          out.write("\n");
          out.write("                        </strong></th>\n");
          out.write("                    </tr>\n");
          out.write("                    </thead>\n");
          out.write("\n");
          out.write("                    <tbody>\n");
          out.write("                    <tr>\n");
          out.write("                        <td colspan=\"2\" style=\"padding:0 !important;\">\n");
          out.write("                            ");

                                if (ArrayUtils.isNotEmpty(roles)) {
                            
          out.write("\n");
          out.write("                            <div style=\"padding:5px 5px 10px 10px\">\n");
          out.write("                                <!-- td>");
          if (_jspx_meth_fmt_005fmessage_005f8(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("</td -->\n");
          out.write("                                ");

                                    String fromPage = "1";
                                    String toPage = String.valueOf(numberOfPages);
                                    if (pageNumber - cachePages >= 0) {
                                        fromPage = String.valueOf(pageNumber + 1 - cachePages);
                                    }
                                    if (pageNumber + cachePages <= numberOfPages - 1) {
                                        toPage = String.valueOf(pageNumber + 1 + cachePages);
                                    }
                                
          out.write("\n");
          out.write("\n");
          out.write("                                <a style=\"cursor:pointer;color:#006699;\" onclick=\"doSelectAll('selectedRoles');\"/>\n");
          out.write("                                ");
          if (_jspx_meth_fmt_005fmessage_005f9(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write(" </a> |\n");
          out.write("                                <a style=\"cursor:pointer;color:#006699;\" onclick=\"doUnSelectAll('selectedRoles');\"/>\n");
          out.write("                                ");
          if (_jspx_meth_fmt_005fmessage_005f10(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write(" </a>\n");
          out.write("                                ");
if (Integer.parseInt(fromPage) < Integer.parseInt(toPage)) {
          out.write("\n");
          out.write("                                | <a style=\"cursor:pointer;color:#006699;\" onclick=\"doSelectAllRetrieved();\"/>\n");
          out.write("                                ");
          if (_jspx_meth_fmt_005fmessage_005f11(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write(' ');
          out.print(fromPage);
          out.write(' ');
          if (_jspx_meth_fmt_005fmessage_005f12(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write(' ');
          out.print(toPage);
          out.write("</a> |\n");
          out.write("                                <a style=\"cursor:pointer;color:#006699;\" onclick=\"doUnSelectAllRetrieved();\"/>\n");
          out.write("                                ");
          if (_jspx_meth_fmt_005fmessage_005f13(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write(' ');
          out.print(fromPage);
          out.write(' ');
          if (_jspx_meth_fmt_005fmessage_005f14(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write(' ');
          out.print(toPage);
          out.write("</a>\n");
          out.write("                                ");
}
          out.write("\n");
          out.write("                            </div>\n");
          out.write("                            ");

                                }
                            
          out.write("\n");
          out.write("                            <table class=\"odd-even-data-table normal\" style=\"width:100%\">\n");
          out.write("                                ");

                                    if (roles != null) {
                                        for (FlaggedName name : roles) {
                                            if (name != null) {
                                                String doCheck = "checked=\"checked\"";
                                                String doEdit = "";
                                                if (name.getItemName().equals(CarbonConstants.REGISTRY_ANONNYMOUS_ROLE_NAME)) {
                                                    continue;
                                                } else if (userRealmInfo.getEveryOneRole().equals(name.getItemName())) {
                                                    doEdit = "disabled=\"disabled\"";
                                                } else if (!name.getEditable()) {
                                                    doEdit = "disabled=\"disabled\"";
                                                } else if (session.getAttribute("checkedRolesMap") != null &&
                                                        Boolean.FALSE.equals(((Map<String, Boolean>) session.getAttribute("checkedRolesMap")).get(name.getItemName()))) {
                                                    doCheck = "";
                                                }
                                
          out.write("\n");
          out.write("                                <tr>\n");
          out.write("                                    <td>\n");
          out.write("                                        <label>\n");
          out.write("                                            <input type=\"checkbox\" name=\"selectedRoles\"\n");
          out.write("                                                   value=\"");
          out.print(Encode.forHtmlAttribute(name.getItemName()));
          out.write('"');
          out.write(' ');
          out.print(doCheck);
          out.write(' ');
          out.print(doEdit);
          out.write(" />\n");
          out.write("                                            ");

                                                if ((name.getItemName()).contains("[Pending Role for Delete]")) {
                                            
          out.write("\n");
          out.write("                                            ");
          out.print(Encode.forHtml(name.getItemDisplayName()));
          out.write("\n");
          out.write("                                            <img src=\"images/workflow_pending_remove.gif\"\n");
          out.write("                                                 title=\"Workflow-pending-user-delete\"\n");
          out.write("                                                 alt=\"Workflow-pending-user-delete\" height=\"15\" width=\"15\">\n");
          out.write("                                            ");

                                            } else {
                                            
          out.write("\n");
          out.write("                                            ");
          out.print(Encode.forHtml(name.getItemName()));
          out.write("\n");
          out.write("                                            ");
if (!name.getEditable()) { 
          out.write(' ');
          out.print("(Read-Only)");
          out.write(' ');

                                                }
                                            } 
          out.write("\n");
          out.write("                                            <input type=\"hidden\" name=\"shownRoles\"\n");
          out.write("                                                   value=\"");
          out.print(Encode.forHtmlAttribute(name.getItemName()));
          out.write("\"/>\n");
          out.write("                                        </label>\n");
          out.write("                                    </td>\n");
          out.write("                                    <td>\n");
          out.write("                                        ");
 if (!userRealmInfo.getAdminRole().equals(name.getItemName())) {
          out.write("\n");
          out.write("                                        <a style=\"background-image:url(images/edit.gif);\" class=\"icon-link\"\n");
          out.write("                                           href=\"../role/edit-permissions.jsp?roleName=");
          out.print(Encode.forUriComponent(name.getItemName()));
          out.write("&prevPage=view&prevUser=");
          out.print(Encode.forUriComponent(userName));
          out.write("&prevPageNumber=");
          out.print(pageNumber);
          out.write('"');
          out.write('>');
          if (_jspx_meth_fmt_005fmessage_005f15(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("</a>\n");
          out.write("                                        ");
} 
          out.write("\n");
          out.write("                                        ");
 if (!userRealmInfo.getEveryOneRole().equals(name.getItemName())) {
          out.write("\n");
          out.write("                                        <a style=\"background-image:url(images/view.gif);\" class=\"icon-link\"\n");
          out.write("                                           href=\"../role/view-users.jsp?roleName=");
          out.print(Encode.forUriComponent(name.getItemName()));
          out.write("&prevPage=view&prevUser=");
          out.print(Encode.forUriComponent(userName));
          out.write("&prevPageNumber=");
          out.print(pageNumber);
          out.write('&');
          out.print(UserAdminUIConstants.ROLE_READ_ONLY);
          out.write('=');
if (!name.getEditable()) { 
          out.write("true");
 }else{ 
          out.write("false");
 } 
          out.write('"');
          out.write('>');
          if (_jspx_meth_fmt_005fmessage_005f16(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("</a>\n");
          out.write("                                        ");
 } 
          out.write("\n");
          out.write("                                    </td>\n");
          out.write("                                    ");
 } 
          out.write("\n");
          out.write("                                </tr>\n");
          out.write("                                ");

                                        }
                                    }
                                
          out.write("\n");
          out.write("                            </table>\n");
          out.write("                        </td>\n");
          out.write("                    </tr>\n");
          out.write("                </tbody>\n");
          out.write("            </table>\n");
          out.write("                ");
          //  carbon:paginator
          org.wso2.carbon.ui.taglibs.Paginator _jspx_th_carbon_005fpaginator_005f1 = (org.wso2.carbon.ui.taglibs.Paginator) _005fjspx_005ftagPool_005fcarbon_005fpaginator_0026_005fparameters_005fpageNumberParameterName_005fpageNumber_005fpage_005fnumberOfPages_005fnoOfPageLinksToDisplay_005faction_005fnobody.get(org.wso2.carbon.ui.taglibs.Paginator.class);
          _jspx_th_carbon_005fpaginator_005f1.setPageContext(_jspx_page_context);
          _jspx_th_carbon_005fpaginator_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
          // /user/view-roles.jsp(487,16) name = pageNumber type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f1.setPageNumber(pageNumber);
          // /user/view-roles.jsp(487,16) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f1.setAction("post");
          // /user/view-roles.jsp(487,16) name = numberOfPages type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f1.setNumberOfPages(numberOfPages);
          // /user/view-roles.jsp(487,16) name = noOfPageLinksToDisplay type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f1.setNoOfPageLinksToDisplay(noOfPageLinksToDisplay);
          // /user/view-roles.jsp(487,16) name = page type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f1.setPage("view-roles.jsp");
          // /user/view-roles.jsp(487,16) name = pageNumberParameterName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f1.setPageNumberParameterName("pageNumber");
          // /user/view-roles.jsp(487,16) name = parameters type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_carbon_005fpaginator_005f1.setParameters("username="+Encode.forHtmlAttribute(userName));
          int _jspx_eval_carbon_005fpaginator_005f1 = _jspx_th_carbon_005fpaginator_005f1.doStartTag();
          if (_jspx_th_carbon_005fpaginator_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fcarbon_005fpaginator_0026_005fparameters_005fpageNumberParameterName_005fpageNumber_005fpage_005fnumberOfPages_005fnoOfPageLinksToDisplay_005faction_005fnobody.reuse(_jspx_th_carbon_005fpaginator_005f1);
            return;
          }
          _005fjspx_005ftagPool_005fcarbon_005fpaginator_0026_005fparameters_005fpageNumberParameterName_005fpageNumber_005fpage_005fnumberOfPages_005fnoOfPageLinksToDisplay_005faction_005fnobody.reuse(_jspx_th_carbon_005fpaginator_005f1);
          out.write("\n");
          out.write("                ");

                    if (ArrayUtils.isNotEmpty(roles) && exceededDomains != null) {
                        if (exceededDomains.getItemName() != null || exceededDomains.getItemDisplayName() != null) {
                            String message = null;
                            if (Boolean.parseBoolean(exceededDomains.getItemName())) {
                                if (StringUtils.isNotBlank(exceededDomains.getItemDisplayName())) {
                                    String arg = "";
                                    String[] domains = exceededDomains.getItemDisplayName().split(":");
                                    for (int i = 0; i < domains.length; i++) {
                                        arg += "\'" + domains[i] + "\'";
                                        if (i < domains.length - 2) {
                                            arg += ", ";
                                        } else if (i == domains.length - 2) {
                                            arg += " and ";
                                        }
                                    }
                                    message = resourceBundle.getString("more.roles.others").replace("{0}", arg);
                                } else {
                                    message = resourceBundle.getString("more.roles.primary");
                                }
                
          out.write("\n");
          out.write("                <strong>");
          out.print(Encode.forHtml(message));
          out.write("\n");
          out.write("                </strong>\n");
          out.write("                ");

                } else if (StringUtils.isNotBlank(exceededDomains.getItemDisplayName())) {
                    String[] domains = exceededDomains.getItemDisplayName().split(":");
                    String arg = "";
                    for (int i = 0; i < domains.length; i++) {
                        arg += "\'" + domains[i] + "\'";
                        if (i < domains.length - 2) {
                            arg += ", ";
                        } else if (i == domains.length - 2) {
                            arg += " and ";
                        }
                    }
                    message = resourceBundle.getString("more.roles").replace("{0}", arg);
                
          out.write("\n");
          out.write("                <strong>");
          out.print(Encode.forHtml(message));
          out.write("\n");
          out.write("                </strong>\n");
          out.write("                ");

                            }
                        }
                    }
                
          out.write("\n");
          out.write("\n");
          out.write("\n");
          out.write("                <tr>\n");
          out.write("                    <td class=\"buttonRow\">\n");
          out.write("                        ");
 if (!showFilterMessage) { 
          out.write("\n");
          out.write("                        <input class=\"button\" type=\"button\" value=\"");
          if (_jspx_meth_fmt_005fmessage_005f17(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\"\n");
          out.write("                               onclick=\"enableCheckBoxes();doUpdate()\"/>\n");
          out.write("                        <input class=\"button\" type=\"button\" value=\"");
          if (_jspx_meth_fmt_005fmessage_005f18(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\"\n");
          out.write("                               onclick=\"enableCheckBoxes();doFinish()\"/>\n");
          out.write("                        ");
} 
          out.write("\n");
          out.write("                        <input class=\"button\" type=\"button\" value=\"");
          if (_jspx_meth_fmt_005fmessage_005f19(_jspx_th_fmt_005fbundle_005f0, _jspx_page_context))
            return;
          out.write("\"\n");
          out.write("                               onclick=\"doCancel()\"/>\n");
          out.write("                    </td>\n");
          out.write("                </tr>\n");
          out.write("        </form>\n");
          out.write("    </div>\n");
          out.write("</div>\n");
          int evalDoAfterBody = _jspx_th_fmt_005fbundle_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fbundle_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_fmt_005fbundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename.reuse(_jspx_th_fmt_005fbundle_005f0);
        return;
      }
      _005fjspx_005ftagPool_005ffmt_005fbundle_0026_005fbasename.reuse(_jspx_th_fmt_005fbundle_005f0);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_csrf_005ftokenname_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  csrf:tokenname
    org.owasp.csrfguard.tag.TokenNameTag _jspx_th_csrf_005ftokenname_005f0 = (org.owasp.csrfguard.tag.TokenNameTag) _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.get(org.owasp.csrfguard.tag.TokenNameTag.class);
    _jspx_th_csrf_005ftokenname_005f0.setPageContext(_jspx_page_context);
    _jspx_th_csrf_005ftokenname_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    int _jspx_eval_csrf_005ftokenname_005f0 = _jspx_th_csrf_005ftokenname_005f0.doStartTag();
    if (_jspx_th_csrf_005ftokenname_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.reuse(_jspx_th_csrf_005ftokenname_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.reuse(_jspx_th_csrf_005ftokenname_005f0);
    return false;
  }

  private boolean _jspx_meth_csrf_005ftokenvalue_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  csrf:tokenvalue
    org.owasp.csrfguard.tag.TokenValueTag _jspx_th_csrf_005ftokenvalue_005f0 = (org.owasp.csrfguard.tag.TokenValueTag) _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.get(org.owasp.csrfguard.tag.TokenValueTag.class);
    _jspx_th_csrf_005ftokenvalue_005f0.setPageContext(_jspx_page_context);
    _jspx_th_csrf_005ftokenvalue_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    int _jspx_eval_csrf_005ftokenvalue_005f0 = _jspx_th_csrf_005ftokenvalue_005f0.doStartTag();
    if (_jspx_th_csrf_005ftokenvalue_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.reuse(_jspx_th_csrf_005ftokenvalue_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.reuse(_jspx_th_csrf_005ftokenvalue_005f0);
    return false;
  }

  private boolean _jspx_meth_csrf_005ftokenname_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  csrf:tokenname
    org.owasp.csrfguard.tag.TokenNameTag _jspx_th_csrf_005ftokenname_005f1 = (org.owasp.csrfguard.tag.TokenNameTag) _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.get(org.owasp.csrfguard.tag.TokenNameTag.class);
    _jspx_th_csrf_005ftokenname_005f1.setPageContext(_jspx_page_context);
    _jspx_th_csrf_005ftokenname_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    int _jspx_eval_csrf_005ftokenname_005f1 = _jspx_th_csrf_005ftokenname_005f1.doStartTag();
    if (_jspx_th_csrf_005ftokenname_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.reuse(_jspx_th_csrf_005ftokenname_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.reuse(_jspx_th_csrf_005ftokenname_005f1);
    return false;
  }

  private boolean _jspx_meth_csrf_005ftokenvalue_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  csrf:tokenvalue
    org.owasp.csrfguard.tag.TokenValueTag _jspx_th_csrf_005ftokenvalue_005f1 = (org.owasp.csrfguard.tag.TokenValueTag) _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.get(org.owasp.csrfguard.tag.TokenValueTag.class);
    _jspx_th_csrf_005ftokenvalue_005f1.setPageContext(_jspx_page_context);
    _jspx_th_csrf_005ftokenvalue_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    int _jspx_eval_csrf_005ftokenvalue_005f1 = _jspx_th_csrf_005ftokenvalue_005f1.doStartTag();
    if (_jspx_th_csrf_005ftokenvalue_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.reuse(_jspx_th_csrf_005ftokenvalue_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.reuse(_jspx_th_csrf_005ftokenvalue_005f1);
    return false;
  }

  private boolean _jspx_meth_csrf_005ftokenname_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  csrf:tokenname
    org.owasp.csrfguard.tag.TokenNameTag _jspx_th_csrf_005ftokenname_005f2 = (org.owasp.csrfguard.tag.TokenNameTag) _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.get(org.owasp.csrfguard.tag.TokenNameTag.class);
    _jspx_th_csrf_005ftokenname_005f2.setPageContext(_jspx_page_context);
    _jspx_th_csrf_005ftokenname_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    int _jspx_eval_csrf_005ftokenname_005f2 = _jspx_th_csrf_005ftokenname_005f2.doStartTag();
    if (_jspx_th_csrf_005ftokenname_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.reuse(_jspx_th_csrf_005ftokenname_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fcsrf_005ftokenname_005fnobody.reuse(_jspx_th_csrf_005ftokenname_005f2);
    return false;
  }

  private boolean _jspx_meth_csrf_005ftokenvalue_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  csrf:tokenvalue
    org.owasp.csrfguard.tag.TokenValueTag _jspx_th_csrf_005ftokenvalue_005f2 = (org.owasp.csrfguard.tag.TokenValueTag) _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.get(org.owasp.csrfguard.tag.TokenValueTag.class);
    _jspx_th_csrf_005ftokenvalue_005f2.setPageContext(_jspx_page_context);
    _jspx_th_csrf_005ftokenvalue_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    int _jspx_eval_csrf_005ftokenvalue_005f2 = _jspx_th_csrf_005ftokenvalue_005f2.doStartTag();
    if (_jspx_th_csrf_005ftokenvalue_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.reuse(_jspx_th_csrf_005ftokenvalue_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fcsrf_005ftokenvalue_005fnobody.reuse(_jspx_th_csrf_005ftokenvalue_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(329,45) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setKey("error.input.validation.msg");
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(337,12) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f1.setKey("roles.list.in.user");
    int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(343,35) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f2.setKey("no.roles.filtered");
    int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(352,28) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f3.setKey("list.roles");
    int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(355,87) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f4.setKey("list.roles");
    int _jspx_eval_fmt_005fmessage_005f4 = _jspx_th_fmt_005fmessage_005f4.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f5 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(360,42) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f5.setKey("user.search");
    int _jspx_eval_fmt_005fmessage_005f5 = _jspx_th_fmt_005fmessage_005f5.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f6 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(379,41) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f6.setKey("role.view.help");
    int _jspx_eval_fmt_005fmessage_005f6 = _jspx_th_fmt_005fmessage_005f6.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f7 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(383,28) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f7.setKey("roles.in.the.user");
    int _jspx_eval_fmt_005fmessage_005f7 = _jspx_th_fmt_005fmessage_005f7.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f8 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f8.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(395,40) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f8.setKey("users");
    int _jspx_eval_fmt_005fmessage_005f8 = _jspx_th_fmt_005fmessage_005f8.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f8);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f9 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f9.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(408,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f9.setKey("select.all.page");
    int _jspx_eval_fmt_005fmessage_005f9 = _jspx_th_fmt_005fmessage_005f9.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f9);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f10 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f10.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(410,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f10.setKey("unselect.all.page");
    int _jspx_eval_fmt_005fmessage_005f10 = _jspx_th_fmt_005fmessage_005f10.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f10);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f11 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f11.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(413,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f11.setKey("select.all.page.from");
    int _jspx_eval_fmt_005fmessage_005f11 = _jspx_th_fmt_005fmessage_005f11.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f11);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f12 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f12.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(413,88) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f12.setKey("select.all.page.to");
    int _jspx_eval_fmt_005fmessage_005f12 = _jspx_th_fmt_005fmessage_005f12.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f12);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f13(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f13 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f13.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f13.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(416,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f13.setKey("unselect.all.page.from");
    int _jspx_eval_fmt_005fmessage_005f13 = _jspx_th_fmt_005fmessage_005f13.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f13);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f13);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f14(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f14 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f14.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f14.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(416,90) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f14.setKey("unselect.all.page.to");
    int _jspx_eval_fmt_005fmessage_005f14 = _jspx_th_fmt_005fmessage_005f14.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f14);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f14);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f15(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f15 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f15.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f15.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(467,228) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f15.setKey("edit.permissions");
    int _jspx_eval_fmt_005fmessage_005f15 = _jspx_th_fmt_005fmessage_005f15.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f15);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f15);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f16(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f16 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f16.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f16.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(472,323) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f16.setKey("view.users");
    int _jspx_eval_fmt_005fmessage_005f16 = _jspx_th_fmt_005fmessage_005f16.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f16);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f16);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f17(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f17 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f17.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f17.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(542,67) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f17.setKey("update");
    int _jspx_eval_fmt_005fmessage_005f17 = _jspx_th_fmt_005fmessage_005f17.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f17);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f17);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f18(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f18 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f18.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f18.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(544,67) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f18.setKey("finish");
    int _jspx_eval_fmt_005fmessage_005f18 = _jspx_th_fmt_005fmessage_005f18.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f18);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f18);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f19(javax.servlet.jsp.tagext.JspTag _jspx_th_fmt_005fbundle_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f19 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f19.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f19.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_fmt_005fbundle_005f0);
    // /user/view-roles.jsp(547,67) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f19.setKey("cancel");
    int _jspx_eval_fmt_005fmessage_005f19 = _jspx_th_fmt_005fmessage_005f19.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f19);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f19);
    return false;
  }
}
